import ldtp
from time import sleep

print ldtp.launchapp('gcalctool')
print ldtp.waittillguiexist('frmCalculator*')
#sleep(2)
#print ldtp.selectmenuitem('frmCalculator*', 'mnuAdvanced')
#sleep(2)
#print ldtp.selectmenuitem('frmCalculator*', 'mnuFinancial')
#sleep(2)
#print ldtp.selectmenuitem('frmCalculator*', 'mnuScientific')
#sleep(2)
#print ldtp.selectmenuitem('frmCalculator*', 'mnuProgramming')
#sleep(2)
#print ldtp.selectmenuitem('frmCalculator*', 'mnuBasic')
#sleep(2)
print ldtp.click('frmCalculator*', 'btnNumeric1')
print ldtp.click('frmCalculator*', 'btnNumeric2')
print ldtp.click('frmCalculator*', 'btnNumeric3')
print ldtp.click('frmCalculator*', 'btnNumeric4')
print ldtp.click('frmCalculator*', 'btnMultiply')
print ldtp.click('frmCalculator*', 'btnNumeric2')
print ldtp.click('frmCalculator*', 'btnCalculateresult')
sleep(4)
print ldtp.selectmenuitem('frmCalculator*', 'mnuQuit')
print ldtp.waittillguinotexist('frmCalculator*')
