#!/usr/bin/env python

import os
import sys
import ldtpd
from optparse import OptionParser

def parse_cmd_line_option():
   usage = "usage: %prog [options]"
   parser = OptionParser(usage)
   parser.add_option("-V", "--version", dest = "version",
                     action = "store_true", help = "LDTP engine version",
                     default = False)
   parser.add_option("-v", "--verbose", dest = "verbose",
                     action = "store_true", help = "Verbose mode",
                     default = False)

   (options, args) = parser.parse_args()
   if options.version:
      # Print version info and exit
      print 'ldtp-2.2.0'
      sys.exit(0)
   if options.verbose:
      # Set verbose flag
      os.environ['LDTP_DEBUG'] = '2'

parse_cmd_line_option()
try:
   ldtpd.main()
except KeyboardInterrupt:
   pass
